// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAazOQn-aiBmrrV_fDfc_QsK5EO6FgDm9E',
    appId: '1:425867921664:web:238df56e3f155a20538be5',
    messagingSenderId: '425867921664',
    projectId: 'mobile-assignment-97bee',
    authDomain: 'mobile-assignment-97bee.firebaseapp.com',
    storageBucket: 'mobile-assignment-97bee.firebasestorage.app',
    measurementId: 'G-5JKMP1LPR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJeOny07koLmvrvTGtAqCyGkhp08PMEFA',
    appId: '1:425867921664:android:cc124068d7ef5b26538be5',
    messagingSenderId: '425867921664',
    projectId: 'mobile-assignment-97bee',
    storageBucket: 'mobile-assignment-97bee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC34UsnO5RvkQgfBg-Drkquu5r0bJ9tOo',
    appId: '1:425867921664:ios:775e9621990b273e538be5',
    messagingSenderId: '425867921664',
    projectId: 'mobile-assignment-97bee',
    storageBucket: 'mobile-assignment-97bee.firebasestorage.app',
    iosBundleId: 'com.example.mobileAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC34UsnO5RvkQgfBg-Drkquu5r0bJ9tOo',
    appId: '1:425867921664:ios:775e9621990b273e538be5',
    messagingSenderId: '425867921664',
    projectId: 'mobile-assignment-97bee',
    storageBucket: 'mobile-assignment-97bee.firebasestorage.app',
    iosBundleId: 'com.example.mobileAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAazOQn-aiBmrrV_fDfc_QsK5EO6FgDm9E',
    appId: '1:425867921664:web:37334995849eb4d8538be5',
    messagingSenderId: '425867921664',
    projectId: 'mobile-assignment-97bee',
    authDomain: 'mobile-assignment-97bee.firebaseapp.com',
    storageBucket: 'mobile-assignment-97bee.firebasestorage.app',
    measurementId: 'G-6QJF215NQT',
  );
}
